version: '4.33'
services:
  playwright-test: 
    image: playwright-test
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run run-chrome
    volumes:
    - ./playwright-report/:/app/playwright-report
    - ./test-results/:/app/test-results